apiVersion: apps.poconetes.dev/v1
kind: Initializer
metadata:
  name: unlock-vault
spec:
  image: ubuntu
  args: [ "touch", "/poco/share/secrets" ]
## /poco/share is shared across all containers and ephemeral
