apiVersion: apps.poconetes.dev/v1
kind: Initializer
metadata:
  name: unlock-vault
spec:
  image: ubuntu
  args: [ "touch", "/pocoshare/secrets" ]
## /pocoshare is shared across all containers and ephemeral
