apiVersion: apps.poconetes.dev/v1
kind: Formation
metadata:
  name: minimal
spec:
  image: paulbouwer/hello-kubernetes:1.5
  minReplicas: 3
  maxReplicas: 5
  environment:
  - name: MESSAGE
    value: hai poco
  ports:
  - name: http
    port: 8080
