apiVersion: apps.poconetes.dev/v1
kind: Application
metadata:
  name: minimal
spec:
  image: paulbouwer/hello-kubernetes:1.5
  formations:
  - name: web-minimal
    minReplicas: 3
    maxReplicas: 5
    environment:
    - name: MESSAGE
      value: hai poco
    ports:
    - name: http
      port: 8080

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: supersite
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - example.poconetes.dev
    secretName: example-tls
  rules:
  - host: example.poconetes.dev
    http:
      paths:
      - path: /
        backend:
          serviceName: web-minimal
          servicePort: 8080
